version: '3.1'

services:

  db:
    build: mysql/
    ports:
        - "8888:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: jaimeles1576483bonnesmontagnesrectangulaires
        MYSQL_DATABASE: camagru
