<?php
$SITE_ADDRESS = "127.0.0.1:8080";
$RESET_PASSWORD_TOKEN_VALIDITY = 1; //In hours
$IMAGE_STORAGE_LOCATION = '/user_images/';
$IMAGE_STORAGE_FULL_LOCATION = $_SERVER["DOCUMENT_ROOT"] . $IMAGE_STORAGE_LOCATION;
$FILTERS_LOCATION = '/views/camera/filters/';
$FILTERS_LOCATION_FULL = $_SERVER["DOCUMENT_ROOT"] . $FILTERS_LOCATION;
$IMAGE_WIDTH = 1280;
$IMAGE_HEIGHT = 720;
$DOCUMENT_ROOT = $_SERVER["DOCUMENT_ROOT"] . '/';